### ISSUE TITLE
特定人物のlevelの上がりを無効にできるようにしてください

### ISSUE THREAD

**Issue by sikkokuhyouma** [sevenc-nanashi/SevenBot-Issues#3]
**提案は今までの問題に関連していますか？説明してください。**
levelを不正にできる問題で、喋っても、levelが上がらないようにする方法がほしいです。

**追加情報**
主に一人ですがベルさんが不正しているので
https://i.gyazo.com/40496276eee4c921f7e5770721db2de9.png
流石にと思い、この提案をします。

**Comment by sikkokuhyouma** [comment]
修正

**Comment by sikkokuhyouma** [comment]
要望再修正しました。

**Comment by sevenc-nanashi** [comment]
ユーザーごとのブーストが実装予定のため、それで0を指定してください。

**Comment by sevenc-nanashi** [comment]
実装したためclose
