### ISSUE TITLE
もう少し軽くしてほしいっす

### ISSUE THREAD

**Issue by komatti365** [sevenc-nanashi/SevenBot-Issues#4]
## バグの説明
ロードがちょっと遅い

## 再現方法
グローバルチャットに新規鯖で接続したときに4-5秒ほどかかった
## 想定
2-3秒(体感)

## 実際
4-5秒(体感)
## 追加情報
なし

**Comment by sevenc-nanashi** [comment]
これはDiscordのレートリミット（スパム防止）の都合上仕様です。
