### ISSUE TITLE
バグ報告

### ISSUE THREAD

**Issue by Req-kun** [sevenc-nanashi/SevenBot-Issues#6]
## バグの説明
level settingsのboostリストを取得できない

## 再現方法
sb.ls b list

## 想定
level settingsのboostリストが送信される

## 実際
バグ説明と同じ

## 追加情報

![](https://media.discordapp.net/attachments/745008730126680117/831820724641333268/image0.png)

**Comment by sevenc-nanashi** [comment]
Fixed
