### ISSUE TITLE
BOTが反応しない

### ISSUE THREAD

**Issue by sisiruirui-sisi** [sevenc-nanashi/SevenBot-Issues#8]
## バグの説明
このissuesに普通のヤツも入れておいてほしいところ
それはともかく、BOTが反応しません

## 再現方法
反応しないので・・・。
コマンドしても反応しない

## 想定
反応する

## 実際
殆どのコマンド反応しない

## 追加情報
ない

**Comment by sevenc-nanashi** [comment]
復旧しました。
